setup/afl_events/urls.py
from django.urls import path
from django.conf.urls import url

from . import views
from afl_events import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.contrib import admin
from afl_events.views import addEvent,PayAmount
from django.conf.urls import include
# from afl_events.checkout import create_checkout_session
# from django.conf.urls import include, path

app_name = 'afl_events'


urlpatterns = [
    # url(r'^registration',views.index),


    url(r'^login_user',views.login_user,name='login_user'),

    url(r'^test',views.test,name='test'),
    # url(r'^login_user',views.login_user,name='login_user'),

    # url(r'^admin_login',views.admin_login,name='admin_login'),
    url(r'^login_admin',views.login_admin,name='login_admin'),

    # url(r'^admin_home',views.admin_home,name='admin_home'),
    url(r'^user_home',views.user_home,name='user_home'),

    url(r'^user_event',views.user_event,name='user_event'),
   

    url(r'^user_logout',views.user_logout,name='user_logout'),
    # url(r'^admin_logout',views.admin_logout,name='admin_logout'),
    url(r'^nsbtest/', views.testcodensb,name='testcode'),


    # -------------------------------------------------
    path('admin/', admin.site.urls),
    url(r'^user-registration',views.register_view,name='registration'),
    # Login and Logout
    path('login/', auth_views.LoginView.as_view(
        template_name='registration/login.html'
        ), 
        name='login'
    ),
    path('logout/', auth_views.LogoutView.as_view(
            next_page='afl/homepage'
        ), 
        name='logout'
    ),
    # path('homepage', TemplateView.as_view(template_name='home.html'), name='homepage'),
    url('homepage/', views.user_home, name='homepage'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'), # new
    path('post/ajax/add_event', addEvent, name = "add_event"),
    # url(r'^checkout/(?P<e_id>\d+)/$', views.Payment_details.as_view(), name='checkout_page'),
    path('checkout/', views.Payment_details.as_view(), name='checkout_page_default'),
    path('checkout/<str:service>', views.Payment_details.as_view(), name='checkout_page'),

    # url(r'^checkout/(?P<e_id>\d+)/$',views.Payment_details.as_view(),name='checkout_page'),
    
]

setup/setup/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
from afl_events import views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    # path(r'^/',views.index,name='index'),
    path('afl/',include('afl_events.urls')),
    path('admin/', admin.site.urls),
    path('payments/stripe', include('stripeintent_subscription.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

setup/templates/add_event.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Add Event</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/add_event.css' %}">
</head>
<body class="bg-primary">
<div class="container-fluid header text-center bg-danger">
<h1 style="color: white">Event Details</h1>
</div>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-lg-6 box bg-danger">
     <center><h1 style="color: white; background-color: green; margin-right: 30px;"> Add Event</h1></center>

      <div class="row justify-content-center">
        <div class="col-lg-6">
          <div class="inputbox">
            <form action="{% url 'afl_events:db_add_event' %}" method="post">
              {% csrf_token %}
              Name of event<br>
              <input type="text" name="name" autocomplete="off" required><br>

              Date<br>
              <input type="date" name="date" autocomplete="off" required><br>

              Time<br>
              <input type="time" name="time" required>

              Duration(hours)<br>
              <input type="number" name="duration" autocomplete="off" required>

              <div class="footer">
                <input type="reset" value="Reset" name="submit">
                <input type="submit" value="Add" name="submit">
              </div>

            </form>
          </div>
        </div>
      </div>
      <a href="{% url 'afl_events:admin_event' %}" class="btn btn-primary" style="color: white;">Back</a>
    </div>
  </div>
</div>

</body>
</html>

setup/templates/admin_login.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>CHMSC | Administration</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static "css/registration.css" %}">
  <style>
  .loginBox{
    margin:80 0 0 0;
    display:block;
  }
  </style>
</head>
<body>

<div class="container-fluid header text-center">
  CHMSC Events Management | Administration
</div>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-lg-6 loginBox">
      Login<br>
      <span style="font-size:18px;">{{ status }}</span>

      <div class="row justify-content-center">
        <div class="col-lg-6">
          <div class="inputBox" style="font-size:18px;">
            <form action="{% url 'afl_events:login_admin' %}" method="post">
              {% csrf_token %}
              Username<br>
              <input type="text" name="name" autocomplete="off" required>

              Password<br>
              <input type="password" name="password" minlength="8" autocomplete="off" required>

              <input type="submit" value="Login" name="login" style="margin:0 25% 0 25%;">
            </form>
          </div>
        </div>
      </div>
      <!-- <a href="#" onclick="navigation(event)" id="regLink">Not a registered user? Register</a> -->

    </div>
  </div>
</div>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script> -->

</body>
</html>

setup/templates/dashboard.html
{% load static %}

<!DOCTYPE html>
<!-- Designined by CodingLab | www.youtube.com/codinglabyt -->
<html lang="en" dir="ltr">
  <head>
    <meta charset="UTF-8">
    <!--<title> Responsiive Admin Dashboard | CodingLab </title>-->
    <link href="{% static 'afl_events/css/style.css' %}" rel="stylesheet" type="text/css" />
    <!-- Boxicons CDN Link -->
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
   </head>
<body>
  <div class="sidebar">
    <div class="logo-details">
      <i class='bx bxl-c-plus-plus'></i>
      <span class="logo_name">Event Management</span>
    </div>
      <ul class="nav-links">
        <li>
          <a href="#" class="active">
            <i class='bx bx-grid-alt' ></i>
            <span class="links_name">Dashboard</span>
          </a>
        </li>
     

        <li>
          <a href="{% url 'afl_events:dashboard' %}" class="active">
            <i class='bx bx-list-ul' ></i>
            <span class="links_name">Event List</span></a>
        </li>
     
        
        {% if user.is_authenticated %}
    
        <li>
          <a href="{% url 'afl_events:logout' %}" class="active">
            <i class='bx bx-log-out' ></i>
            <span class="links_name">Logout</span></a>
        </li>

        {% endif %}


      </ul>
  </div>
  <section class="home-section">
    <nav>
   
      <div class="sidebar-button">
        <i class='bx bx-menu sidebarBtn'></i>
        <span class="dashboard">Dashboard</span>
      </div>
     
      <div class="profile-details">
        <!--<img src="images/profile.jpg" alt="">-->
        <span class="admin_name">
        {% if user.is_authenticated %}
        <p>{{user.first_name}} {{user.last_name}}</p>
        <p>{{user.email}}</p></span>
        {% endif %}
        <!-- <i class='bx bx-chevron-down' ></i> -->
      </div>
    </nav>

    <div class="home-content">
      <div class="overview-boxes">
        <div class="box">
          <div class="right-side">
            <div class="box-topic">Total Events</div>
            <div class="number">40,876</div>
            <div class="indicator">
              <i class='bx bx-up-arrow-alt'></i>
              <span class="text">Up from yesterday</span>
            </div>
          </div>
          <i class='bx bx-cart-alt cart'></i>
        </div>
        <div class="box">
          <div class="right-side">
            <div class="box-topic">Next Event</div>
            <div class="number">38,876</div>
            <div class="indicator">
              <i class='bx bx-up-arrow-alt'></i>
              <span class="text">Up from yesterday</span>
            </div>
          </div>
          <i class='bx bxs-cart-add cart two' ></i>
        </div>
        <div class="box">
          <div class="right-side">
            <div class="box-topic">Total Payment</div>
            <div class="number">$12,876</div>
            <div class="indicator">
              <i class='bx bx-up-arrow-alt'></i>
              <span class="text">Up from yesterday</span>
            </div>
          </div>
          <i class='bx bx-cart cart three' ></i>
        </div>
        <div class="box">
          <div class="right-side">
            <div class="box-topic">Active Events </div>
            <div class="number">11,086</div>
            <div class="indicator">
              <i class='bx bx-down-arrow-alt down'></i>
              <span class="text">Down From Today</span>
            </div>
          </div>
          <i class='bx bxs-cart-download cart four' ></i>
        </div>
      </div>

      <div class="sales-boxes">
        <div class="recent-sales box">
          <div class="title">Events list</div>
          <table>
            <tr>
              {% for key,val in headers.items %}
              <th>{{val}}</th>
              {% endfor %} 
            </tr>

          {% for event in evnt %} 
            <tr>
              <td> {{ event.eid }}</td>
              <td> {{ event.name }} </td>
              <td>{{event.date}}</td>
              <td>{{event.time}}</td>
              <td>{{event.duration}}</td>
              <!-- <td><a class="btn btn-primary" href ="{ % abs_url afl_events:checkout_page %}"> Pay</a></td> -->
              <form id="pay-amnt" class ="pay-amnt" method="POST" >
                  
              <td>
                  {% csrf_token %}
                <!-- <button name="button" type="submit" id="pay-amnt"  >Pay Amount</button> -->
                <button type="button" class="btn btn-info btn-sm pay-amnt1" id="pay-amnt1"  data-toggle="modal" data-target="#mypayment" >Pay Amount</button>
              </td>
              </form>
            </tr>
          {% endfor %} 
  
          </table>
          
          
          
          <!-- Trigger the modal with a button -->
          <button type="button" class="btn btn-info btn-sm addevnmdl"  data-toggle="modal" data-target="#myModal">New Event</button>
        
          <!-- Modal -->
          <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">
            
              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">

             
             
                 <form id="add-event">
                  <div class="row">

                      {% csrf_token %}
                      {% for field in addevntform %}
                      <div class="row g-3 " style="
                      padding-left: 17px;
                      padding-right: 38px; ">
                            

                      <div class="form-group">
                        <label class="col-md-6 mt-md-0 mt-3" for="{{form.field.auto_id}}">{{field.label}}</label>
                        <div class="col-md-6 mt-md-0 mt-3" id ="{{form.field.auto_id}}">
                          {{field}}
                        </div>
                      </div>
                    </div>
                      {% endfor %}

                      <input type="submit" class="btn btn-primary float-right" value="Create Event"style="margin-left: 15px;">
                      
                    </form>


                    </div>
                </div>

                    <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

                    </div>
                </div>
              </div>
              




             
            </div>
          </div>
                    
        </div>


        </div>
     
    </div>

     <!----payment section-------->

     <div class="modal fade" id="mypayment" role="dialog">
        <div class="modal-dialog">
        
          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">

         
         
             <form id="add-payment" method="POST" class="m-form" action="{{request.path}}"  enctype="multipart/form-data" autocomplete="off" novalidate>
              <div class="row">

                  {% csrf_token %}
                  {% for field in paymentoptionform %}
                  <div class="row g-3 " style="
                  padding-left: 17px;
                  padding-right: 38px; ">
                        

                  <div class="form-group">
                    <label class="col-md-6 mt-md-0 mt-3" for="{{form.field.auto_id}}">{{field.label}}</label>
                    <div class="col-md-6 mt-md-0 mt-3" id ="{{form.field.auto_id}}">
                      {{field}}
                    </div>
                  </div>
                </div>
                  {% endfor %}

                  <input type="submit" id ="pay-now" class="btn btn-primary float-right" value="Pay Now"style="margin-left: 15px;">
                  
                </form>


                </div>
            </div>

                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>

                </div>
            </div>
          </div>
  </section>

  <script>
    
   let sidebar = document.querySelector(".sidebar");
let sidebarBtn = document.querySelector(".sidebarBtn");
sidebarBtn.onclick = function() {
  sidebar.classList.toggle("active");
  if(sidebar.classList.contains("active")){
  sidebarBtn.classList.replace("bx-menu" ,"bx-menu-alt-right");
}else
  sidebarBtn.classList.replace("bx-menu-alt-right", "bx-menu");
}


$("#add-event").submit(function (e) {
 
    // preventing from page reload and default actions
    e.preventDefault();
    // serialize the data for sending the form data.
    var serializedData = $(this).serialize();
 
    // make POST ajax call
    $.ajax({
        type: 'POST',
        url: "{% url 'afl_events:add_event' %}",
        data: serializedData,
        success: function (response) {
            // on successfull creating object
            // 1. clear the form.
            $("#add-event").trigger('reset');
            // 2. focus to nickname input 

        },
        error: function (response) {
            // alert the error if any error occured
            alert(response["responseJSON"]["error"]);
        }
    })

    $(function () {
      $('#myModal').modal('toggle');
    });
    window.location.reload();
})

// $("#pay-amnt").submit(function (e) {
//  alert("alerttt")
//  // preventing from page reload and default actions
//  e.preventDefault();
//  // serialize the data for sending the form data.
//  var serializedData = $(this).serialize();
//  console.log("serializedData")
//  console.log(serializedData)

//   // Generate URL without "id" bit
//   var url = "{% url 'afl_events:checkout_page_default'  %}";

//   var id = $(this).attr('id');

//   // Construct the full URL with "id"
//   document.location.href = url+serializedData['choice'] ;

//  // make POST ajax call
 

 
// })
// $(".pay-amnt").submit(function (e) {
//   alert('fgghghg')

//  e.preventDefault();
//  $('#mypayment').modal('toggle');

 
// })
$("#add-payment").submit(function (e) {
 alert("alerttt")
 // preventing from page reload and default actions
 e.preventDefault();
 // serialize the data for sending the form data.



  // Generate URL without "id" bit
  var url = "{% url 'afl_events:checkout_page_default'  %}";

  var id = $(this).attr('id');

  // Construct the full URL with "id"
  document.location.href = url+$('select[name="choice"]').val() ;

 // make POST ajax call
 

})
 </script>

{% block javascript %}

  <script src="{% static 'afl_events/js/event.js' %}" type="text/javascript"></script>
{% endblock %}


</body>
</html>

setup/templates/home.html
<!-- home.html -->
{% extends 'base.html' %}

{% block title %}Home Page{% endblock title %}

{% block content %} 
    <h2>Home</h2>
    {% if user.is_authenticated %}
    <p>You are welcome on Home Page</p>
    <p>Your name is - {{user.first_name}} {{user.last_name}}</p>
    <p>Your email is - {{user.email}}</p>
    <br><br>
    <a href="{% url 'afl_events:logout' %}">Logout</a>
    {% else %}
    <a href="{% url 'afl_events:login' %}">Login</a>
    {% endif %}
{% endblock content %}

setup/templates/payment.html
{% extends "base.html" %}
<!-- templates/payment.html -->
{% block css %} 
{% endblock css %}
{% block headjavascript %}
 {% endblock headjavascript %}

{% block content %}

<div class="wrapper-content">
        <div class="cart-wrapper">
            <div class="container inner-container">
                <div class="cart-wizard-wrapper py-35">
                    <div class="cart-wizard-inner">
             <div class="test-payment-div">
              <!-- templates/payment.html -->
              <form action="{{ form.action }}" method="{{ form.method }}">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <p><input type="submit" value="Proceed" /></p>
                </form>
              </div>
            </div>
         </div>
        </div>
      </div>
    </div>
{% endblock content %}
{% block javascript %}
 {% endblock javascript %}

setup/templates/register.html
register
<form method="post">
   {{form.as_table}} 
   {% csrf_token %}
   <input type="submit" value="Register">
</form>   

setup/templates/registration.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Registration| Welcome</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{% static "css/registration.css" %}">
  <script type="text/javascript" src="{% static "js/main.js" %}"></script>
</head>
<body class="bg-success">

<div class="container-fluid header text-center bg-primary">
  <h1 style="color: white;">CHMSC Events Management System</h1>
</div>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-0 btn-bar" onclick="navigation(event)">
      <a href="#" class="myactive" id="registration">Registration</a>
      <a href="#" class="" id="login">Login</a>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-lg-6 box bg-danger" style="display:block;">
      <!-- <span style="font-size:26px;">Registration</span> -->
      <center><h1 class="bg-primary" style="color: white; margin-right: 30px;"> Registration</h1></center>
      <span style="font-size:18px;">{{ status }}</span>

      <div class="row justify-content-center">
        <div class="col-lg-6">
          <div class="inputbox">
            <form action="{% url 'afl_events:test' %}" method="post">
              {% csrf_token %}
              Username<br>
              <input type="text" name="uname" autocomplete="off" required><br>

              E-Mail<br>
              <input type="text" name="email" autocomplete="off" required><br>

              Gender<br>
              <input type="radio" name="gender" value="Male"> Male
              <input type="radio" name="gender" value="Female"> Female<br>

              Password<br>
              <input type="password" name="password" minlength="8" autocomplete="off" required><br>

              Re-enter Password<br>
              <input type="password" name="repassword" minlength="8" autocomplete="off" required>

              <input type="submit" value="Submit" name="submit" style="margin:0 25% 0 25%;">
            </form>
          </div>
        </div>
    </div>
    <a href="#" onclick="navigation(event)" id="loginLink" style="color: white;">Already registered? Login</a>

    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-lg-6 loginBox bg-danger" style="display:none;">
      <center><h1 class="bg-primary" style="color: white; margin-right: 30px;">Login</h1></center>

      <div class="row justify-content-center">
        <div class="col-lg-6">
          <div class="inputBox" style="font-size:18px;">
            <form action="{% url 'afl_events:login_user' %}" method="post">
              {% csrf_token %}
              Username<br>
              <input type="text" name="name" autocomplete="off" required><br>

              Password<br>
              <input type="password" name="password" minlength="8" autocomplete="off" required>

              <input type="submit" value="Login" name="login" style="margin:0 25% 0 25%;">
            </form>
          </div>
        </div>
      </div>
      <a href="#" onclick="navigation(event)" id="regLink" style="color: white;">Not a registered user? Register</a>

    </div>
  </div>
</div>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script> -->

</body>
</html>

setup/templates/sidebar.html
<div class="sidebar">
    <div class="logo-details">
      <i class='bx bxl-c-plus-plus'></i>
      <span class="logo_name">Event Management</span>
    </div>
      <ul class="nav-links">
        <li>
          <a href="#" class="active">
            <i class='bx bx-grid-alt' ></i>
            <span class="links_name">Dashboard</span>
          </a>
        </li>
        <li>
          <a href="#">
            <i class='bx bx-box' ></i>
            <span class="links_name">Event List</span>
          </a>
        </li>
        {% if user.is_authenticated %}
        <li class="log_out">
          <a href="#">
            <i class='bx bx-log-out'></i>
            <a href="{% url 'afl_events:logout' %}">Logout</a>

            <span class="links_name">Log out</span>
          </a>
        </li>
        {% endif %}


      </ul>
  </div>

setup/templates/user_home.html
<!DOCTYPE html>
{% load static %}

<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Event Management System</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"> -->

  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto+Mono:400,500,700&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Muli:500&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>

<body class="bg-success">
<div class="container-fluid header text-center bg-primary">
  <h1 style="color: white;">CHMSC Events Management System</h1>
  <h3 style="color: white;"> Welcome {{ name }} </h3>
  <a href="{% url 'afl_events:user_logout' %}" style="font-size:20; color: white;">Logout</a><br>
  <span style="font-size:18px">{{ status }}</span>
</div>

<div class="container">
  <div class="row">
    <div class="col-lg-6">
      <a href="{% url 'afl_events:user_event' %}">
      <div class="card bg-danger">
        <img src="{% static 'res/event.jpeg' %}">
        <div class="card-title text-center" style="color: white;">Events</div>
      </div>
      </a>
    </div>

    

  </div>
</div>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script> -->

</body>
</html>