setup/setup/urls.py
from django.contrib import admin
from django.urls import path

from django.conf.urls import include
from afl_events import views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    # path(r'^/',views.index,name='index'),
    path('afl/',include('afl_events.urls')),
    path('admin/', admin.site.urls),
    path('payments/stripe', include('stripeintent_subscription.urls')),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

setup/stripeintent_subscription/urls.py
from django.conf.urls import url
from django.urls import path
from . import views as stripeintent_subscription
app_name = 'stripeintent_subscription'

urlpatterns = [


	path('stripe-intent/intent/publickey/', stripeintent_subscription.StripePaymentIntentPublicKeyView.as_view(), name='public_key')
]

setup/stripeintent_subscription/models.py
from django.db import models
from django.utils import timezone
from django.contrib import admin
#from afl_core.afl_common.utilities import AflGetOptionFromList
from django.utils.text import slugify
# Create your models here.

class StripeIntentCard(models.Model):
	setup_intent = models.CharField(max_length=1000, default='', null=True,blank=True) #Stripe Payment Method
	class Meta:
		managed = False	
class StripeIntentSubscriptionOption(models.Model):
	uid = models.IntegerField(default=0, blank=True)
	class Meta:
		managed = False	

class StripeIntentPaymentCheck(models.Model):
	order_number = models.CharField(max_length=200, default='')
	
	class Meta:
		managed = False	

setup/stripeintent_subscription/forms.py
from __future__ import unicode_literals

from payments.forms import CreditCardPaymentForm
from payments import PaymentStatus
from collections import OrderedDict
from payments.utils import get_month_choices, get_year_choices
from payments import FraudStatus, PaymentStatus, RedirectNeeded
from django.utils.translation import ugettext as _
from payments.forms import PaymentForm as BasePaymentForm
from django import forms
RESPONSE_STATUS = {
	'1': PaymentStatus.CONFIRMED,
	'2': PaymentStatus.REJECTED}


import copy
import json
import traceback

class StripeIntentPaymentForm(BasePaymentForm):
	class Media:
		js = ['stripeintent_subscription/js/stripe_payment_intent.js',]

	payment_id = forms.CharField(widget=forms.HiddenInput())
	payment_intent = forms.CharField(widget=forms.HiddenInput(),initial=0)
	status = forms.CharField(widget=forms.HiddenInput(),initial=0)
	def __init__(self, *args, **kwargs):
		
		super(StripeIntentPaymentForm, self).__init__( hidden_inputs=False,  *args, **kwargs)
		self.template ="payment_stripe.html"
		self.init_load()
		self.assign()
		self.redirect_success_status = True
		#set fields
		self.set_field()
		if 'keyOrder' in self.fields:
			self.fields.keyOrder = self.fields_key_order
		else:
			self.fields = OrderedDict((k, self.fields[k]) for k in self.fields_key_order)
	def init_load(self):
		if self.data:
			import stripe
			self.stripe = stripe
			
			self.public_key =''
			self.secret_key =''
			self.customer =''

			self.public_key = self.provider.public_key

			self.secret_key = self.provider.secret_key
			if self.secret_key and self.public_key:
				self.stripe.api_key = self.secret_key
	def assign(self):
		self.fields_key_order =[]
	def set_field(self):
		self.fields_key_order.extend(('payment_intent','payment_id','status'))
		self.fields['payment_id'].initial = self.payment.pk
	def clean(self):
		self.cleaned_data = super(StripeIntentPaymentForm, self).clean()

		try:
			
			self.clean_new_card()
			
		except self.stripe.error.CardError as e:
			# Making sure we retrieve the charge
			err = e.error
			import traceback
			traceback.print_exc()
			
			# The card has been declined
			self._errors['__all__'] = self.error_class([str(err['message'])])
			
			self.payment.change_status(PaymentStatus.ERROR, str(err['message']))
		except Exception as e:
			#log the message
			import traceback
			traceback.print_exc()
			logger_error.error(e)
			self._errors['__all__'] = self.error_class([str(e)])
		

		return self.cleaned_data
	def clean_new_card(self):
		self.stripe_retrieve = self.stripe.PaymentIntent.retrieve(
					self.cleaned_data['payment_intent'],
				)
		if (self.stripe_retrieve
			and
			'order_number' in self.stripe_retrieve['metadata'] 
			and 
			self.cart
			and
			self.stripe_retrieve['metadata']['order_number'] ==str(self.order.order_number)
		):
			pass
		else:

			self.redirect_success_status ==False
	def get_amount(self):
		
		return int(self.payment.total*100),self.payment.currency.lower()
	
	def save(self):
		self.payment.transaction_id = self.stripe_retrieve['id']
		self.payment.attrs.charge = self.stripe_retrieve
		self.payment.change_status(PaymentStatus.PREAUTH)
		if self.provider._capture:
			self.payment.capture()
		# Make sure we store the info of the charge being marked as fraudulent
		self._handle_potentially_fraudulent_charge(self.stripe_retrieve)

	def _handle_potentially_fraudulent_charge(self, charge, commit=True):
		# fraud_details = charge['fraud_details']
		# if fraud_details.get('stripe_report', None) == 'fraudulent':
		# 	self.payment.change_fraud_status(FraudStatus.REJECT, commit=commit)
		# else:
			self.payment.change_fraud_status(FraudStatus.ACCEPT, commit=commit)

	

setup/stripeintent_subscription/views.py
from django.shortcuts import render
from django.views import View
# Create your views here.
from django.dispatch import receiver,Signal
from django.http import HttpResponse,HttpResponseRedirect, JsonResponse
from django.utils.translation import ugettext as _
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import permission_required,login_required
from django.http import QueryDict
from django.conf import settings
from django.forms.formsets import formset_factory
from django.template.loader import render_to_string
from django.core.paginator import Paginator
from .models import *

from django.contrib import messages
from django.forms.models import modelformset_factory
from django.views.decorators.csrf import csrf_exempt
from django.template.response import TemplateResponse
from django.core.exceptions import PermissionDenied
import traceback
from payments import get_payment_model, RedirectNeeded
from payments import FraudStatus, PaymentStatus, RedirectNeeded
import copy
import datetime
import stripe
import json

class StripePaymentIntentPublicKeyView(View):
	#@method_decorator(csrf_exempt)
	def dispatch(self, request, *args, **kwargs):
		self.stripe = stripe
		stripe_conf = settings.PAYMENT_VARIANTS['stripeintent_subscription'][1]
		print(stripe_conf)
		self.public_key =''
		self.secret_key =''
		self.customer =''
		if stripe_conf:
			if 'public_key' in stripe_conf:
				self.public_key = stripe_conf['public_key']
		if stripe_conf:
			if 'secret_key' in stripe_conf:
				self.secret_key = stripe_conf['secret_key']
		if self.secret_key and self.public_key:
			self.stripe.api_key = self.secret_key
			
		self.order =None
		ORDER_ID=""
		self.order_id = request.session.get(ORDER_ID)
		self.data ={}
		self.user_data ={}
		self.stripesyscustomer =None
		self.save_customer_status =False
		self.payment =None
		self.customer =None
		self.cart =None
		self.transaction_object =None
		return super(StripePaymentIntentPublicKeyView, self).dispatch(request, *args, **kwargs)
	def get(self, request, *args, **kwargs):
		data ={'publicKey': self.public_key}
		
		response =  JsonResponse(data , safe=False)
		return response
	def post(self, request, *args, **kwargs):
		pp('******pay_postrequest.POSTdddd************')
		pp(request.POST)
		pp(list(request.POST)[0])
		pp(json.loads(list(request.POST)[0]))
		self.data = json.loads(list(request.POST)[0])
		cart_kwargs={
					'new_order':False
				}
		self.get_queryset()
		return self.pay_post()
		#return render(request, 'afl_commerce/afl_payment/stripe_subscription/test.html',{}) 
	def get_queryset(self):
		
		paymentModel = get_payment_model()
		self.payment = paymentModel.objects.filter(pk=int(self.data['payment_id'])).first()
	def get_amount(self):
		return int(100*100),'usd'
	
	def cart_errors_actions(self):
		if  self.cart.errors:
			message =""
			redirect_url =""
			response ={}
			for  module ,cart_module_errors in  self.cart.errors.items():
				for cart_module_error in cart_module_errors['message']:
					message = str(cart_module_error)
					response.update({
						'error':message
					})
				if 'redirect_url' in cart_module_errors:
					redirect_url =  cart_module_errors['redirect_url']
					response.update({
						'redirect_url':redirect_url
					})
			if self.order:
				self.order.order_convert_review_pending(self.cart)
			return JsonResponse(response, safe=False)
	def pay_post(self):
		pp('*****************pay_postfghghgh***************')
		try:
			
			if "paymentIntentId" not in self.data and self.payment:
				if 'cancel' in self.data and self.data['cancel']==True:
					
					return JsonResponse({'error': str('Your card was not authenticated, please try again')}, safe=False)
				else:
					
					
					amount,currency_code = self.get_amount()
					payment_intent_data = dict(
						amount=amount,
						currency=currency_code,
						payment_method=self.data['paymentMethodId'],
						confirmation_method='manual',
						confirm=True,
						metadata={
							'order_number':'test123',
						},
						#description='Email:%s' % (self.user_data['email'])
						description='Order Number: %s' % (
							'test123',
							),

						shipping = {
							"name": "Jenny Rosen",
							"address": {
							"line1": "510 Townsend St",
							"postal_code": "98140",
							"city": "San Francisco",
							"state": "CA",
							"country": "US",
							},
						},
					)
					# if self.save_customer_status:
					# 	# get or set customer using api
					# 	self.get_or_set_stripe_customer()
					# 	#if self.data['isSavingCard']:
					# 	# Create a Customer to store the PaymentMethod for reuse
						
						

					# 	payment_intent_data['customer'] = self.customer['id']
					# 	# Set save_payment_method to true to attach the PM to the Customer
					# 	payment_intent_data['save_payment_method'] = True

					# 	# setup_future_usage tells Stripe how you plan on using the saved card
					# 	# set to 'off_session' if you plan on charging the saved card when the customer is not present
					# 	payment_intent_data['setup_future_usage'] = 'off_session'

						# Create a new PaymentIntent for the order
					intent =self.stripe.PaymentIntent.create(**payment_intent_data)
			else:
				# Confirm the PaymentIntent to collect the money
				intent =self.stripe.PaymentIntent.confirm(self.data['paymentIntentId'])
				
			return self.generate_response(intent)
		except self.stripe.error.CardError as e:
			
			message =str('Some error occured.Please try again later')
			if hasattr(e,'_message'):
				message = str(e._message)
			elif hasattr(e,'error'):
				err = e.error
				traceback.print_exc()
				# The card has been declined
				return JsonResponse({'error': str(err['message'])}, safe=False)
			else:
				return JsonResponse({'error': str('Some error occured.Please try again later')}, safe=False)
			return JsonResponse({'error': message}, safe=False)
		
			
		except Exception as e:
			message =  "some error occure.Please try again later"
			if hasattr(e,'_message'):
				message = str(e._message)
			traceback.print_exc()
		
			return JsonResponse({'error':message}, safe=False)
	def generate_response(self,intent):
		status = intent['status']
		if status == 'requires_action' or status == 'requires_source_action':
			# Card requires authentication
			return JsonResponse({'requiresAction': True, 'paymentIntentId': intent['id'], 'clientSecret': intent['client_secret']}, safe=False)
		elif status == 'requires_payment_method' or status == 'requires_source':
			# Card was not properly authenticated, suggest a new payment method
			return JsonResponse({'error': 'Your card was denied, please provide a new payment method'}, safe=False)
		elif status == 'succeeded':
			# Payment is complete, authentication not required
			# To cancel the payment after capture you will need to issue a Refund (https://stripe.com/docs/api/refunds)
			pp("Pay33ment received!")
			
			
			#save customer in db
			self.save_payment(intent)
			return JsonResponse({'clientSecret': intent['client_secret']}, safe=False)
	
	def save_payment(self,intent):

		self.payment.transaction_id = intent['id']
		self.payment.attrs.charge = json.dumps(intent)
		self.payment.change_status(PaymentStatus.PREAUTH)
		
		self.payment.capture()
		# Make sure we store the info of the charge being marked as fraudulent
		self._handle_potentially_fraudulent_charge(intent)
		pass
	
	
	def _handle_potentially_fraudulent_charge(self, charge, commit=True):
		pp('******************fraudulent_charges************')
		# fraud_details = charge['fraud_details']
		# if fraud_details.get('stripe_report', None) == 'fraudulent':
		# 	self.payment.change_fraud_status(FraudStatus.REJECT, commit=commit)
		# else:
		self.payment.change_fraud_status(FraudStatus.ACCEPT, commit=commit)

'''
#######################
end check stripe intent payment
######################
'''

setup/stripeintent_subscription/templates/payment_stripe.html
{% extends "base.html" %}
{% load static %}
{% block headjavascript %}
<script src="https://js.stripe.com/v3/"></script>

{% endblock %}
{% block content %}


<div class="wrapper-content">
	<div class="cart-wrapper">
		<div class="container inner-container">
			<div class="cart-wizard-wrapper py-35">
				<div class="cart-wizard-inner">
					<div class="m-portlet__body stripe-card-container">
						<form method="{{form.method|default:'POST'}}" class="{{form.class}} m-form m-form--fit m-form--label-align-right" action="{{form.action|default:request.path}}"  {% if files %} enctype="multipart/form-data"{% endif %} autocomplete="off" novalidate >
							
								{% csrf_token %}
								<div class="container-fluid">
									{% if form.non_field_errors %}
									<div class="alert alert-danger" role="alert">
										{% for error in form.non_field_errors %}
											{{ error }}
										{% endfor %}
									</div>
									{% endif %}
									
									{% for hidden_field in form.hidden_fields %}
										{% if hidden_field.errors %}
										<div class="alert alert-danger alert-dismissible fade show" role="alert">
											<button type="button" class="close" data-dismiss="alert" aria-label="Close">
												<span aria-hidden="true">&times;</span>
											</button>
											{% for error in hidden_field.errors %}
												(Hidden field {{ hidden_field.name }}) {{ error }}
											{% endfor %}
											
										</div>
										{% endif %}
										{{hidden_field}}
									{% endfor %}
								</div>

								<div class="form-group m-form__group payment-last-wrapper">
									<div class="row no-gutters">
										
										<div class="credit-card col-md-8">
											<div class="new-card-details">
												{{ form.as_p }}
												<div class="sr-input sr-card-element" id="card-element"></div>
											</div>
											<div class="m-portlet__foot m-portlet__foot--fit pl-2 col-md-12">
												<button 
												type="Submit"
												class="bitaps_button_confirm btn btn-brand"
												style='white-space:normal'
											
												label="Pay Now"
												
												initial-url={% url 'stripeintent_subscription:public_key'  %}
												pay-url={% url 'stripeintent_subscription:public_key'  %}
												id='stripe-submit-button'
												
												>Pay Amount</button>
											</div>
											
										</div>
										
									</div>
								</div>
							
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}


{% block css %}
<style type="text/css">



    .form-eps-group{margin:20px 0 10px;position:relative;}
    .form-eps-group label{padding:10px;pointer-events:none;position:absolute;left:15px;top:5px;transition:0.2s;transition-timing-function:ease;transition-timing-function:cubic-bezier(0.25, 0.1, 0.25, 1);opacity:0.5;font-size:1rem;}
    .form-eps-group input:focus+label{opacity:1;transform:scale(0.75) translateY(-100%) translateX(-30px);}
    .form-eps-group input:is(:placeholder-shown)+label{opacity:1;transform:scale(0) translateY(-100%) translateX(-30px);}
    .form-eps-group.open>label{opacity:1;transform:scale(0.75) translateY(-100%) translateX(-30px);}
    .form-eps-group input:is(:-ms-input-placeholder)+label{opacity:1;transform:scale(0.75) translateY(-100%) translateX(-30px);}
    .form-eps-group .select2-container--default .select2-selection--single .select2-selection__rendered{line-height: 42px;}
    </style>
{% endblock %}

{% block javascript %}
<script type="text/javascript">

	$(document).ready(function() {

		$(':input').removeAttr('placeholder');

	});

</script>
{% if form.media %}
	{{form.media}}
{% endif %}
{% endblock %}